{% set version = '0.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mendelianrandomization
  version: {{ version|replace("-", "_") }}

source:
  url:     {{ cran_mirror }}/src/contrib/Archive/MendelianRandomization/MendelianRandomization_{{ version }}.tar.gz
  sha256: 6d4a4c6f2514720391d2bf70bc35d524b7fcdd54df4d5420086725d8ee5efd84

build:
  merge_build_host: True  # [win]
  number: 0

  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-matrix >=1.2
    - r-ggplot2 >=1.0.1
    - r-iterpc >=0.3
    - r-knitr
    - r-plotly >=3.6.0
    - r-rjson
    - r-rmarkdown
    - r-robustbase >=0.92_6

  run:
    - r-base
    - r-matrix >=1.2
    - r-ggplot2 >=1.0.1
    - r-iterpc >=0.3
    - r-knitr
    - r-plotly >=3.6.0
    - r-rjson
    - r-rmarkdown
    - r-robustbase >=0.92_6

test:
  commands:
    - $R -e "library('MendelianRandomization')"           # [not win]
    - "\"%R%\" -e \"library('MendelianRandomization')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MendelianRandomization
  license: GPL-2.0 OR GPL-3.0
  summary: Encodes several methods for performing Mendelian randomization analyses with summarized
    data. Summarized data on genetic associations with the exposure and with the outcome
    can be obtained from large consortia. These data can be used for obtaining causal
    estimates using instrumental variable methods.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - alhenry


# Package: MendelianRandomization
# Type: Package
# Title: Mendelian Randomization Package
# Version: 0.4.0
# Date: 2019-03-06
# Author: Olena Yavorska <olena.yavorska@ludwig.ox.ac.uk> James Staley <james.staley@bristol.ac.uk>
# Maintainer: Stephen Burgess <sb452@medschl.cam.ac.uk>
# Description: Encodes several methods for performing Mendelian randomization analyses with summarized data. Summarized data on genetic associations with the exposure and with the outcome can be obtained from large consortia. These data can be used for obtaining causal estimates using instrumental variable methods.
# License: GPL-2 | GPL-3
# Depends: R (>= 3.0.1), methods
# Imports: knitr, rmarkdown, plotly (>= 3.6.0), ggplot2 (>= 1.0.1), robustbase (>= 0.92-6), Matrix (>= 1.2), iterpc (>= 0.3), rjson
# VignetteBuilder: knitr
# LazyData: TRUE
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-03-07 11:03:38 UTC; stephenb
# Repository: CRAN
# Date/Publication: 2019-03-07 11:33:29 UTC
